#!/usr/bin/env python

import sys
from tiddlywebwiki import twinstance
from tiddlywebplugins.utils import get_store
from tiddlyweb.config import config

from tiddlywebplugins.imaker import Instance

def check_instance():
    store = get_store(config)

    try:
        if len(store.list_recipes()):
            return
    except Exception as exc:
        sys.write.stderr('failing to determine deployment status: %s'
                % exc)
        return

    instance = Instance('.', config)
    store_structure = getattr(twinstance, 'store_structure', {})
    instance._init_store(store_structure)

    for package_name in config.get('instance_pkgstores', []):
        source_store = Store('tiddlywebplugins.pkgstore',
                {'package': package_name, 'read_only': True},
                {'tiddlyweb.config': config)
        for bag in source_store.list_bags():
            for tiddler in source_store.list_bag_tiddlers(bag):
                tiddler = source_store.get(tiddler)
                store.put(tiddler)

if __name__ == '__main__':
    check_instance()
